default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.1'
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v2.18.0'
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.4.0'
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.31.0'
    hooks:
      - id: yapf
        additional_dependencies: [toml]
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.25.1'
    hooks:
      - id: pyupgrade
  - repo: https://github.com/yoheimuta/protolint
    rev: 'v0.34.0'
    hooks:
      - id: protolint
  # - repo: https://github.com/markdownlint/markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 'v0.28.1'
    hooks:
      - id: markdownlint
  - repo: https://github.com/rubocop/rubocop
    rev: 'v1.20.0'
    hooks:
      - id: rubocop
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 'v0.7.2.1'
    hooks:
      - id: shellcheck
  - repo: https://github.com/cpplint/cpplint
    rev: '1.6.0'
    hooks:
      - id: cpplint
        args: ['--linelength=100']
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: 'v0.6.13'
    hooks:
      - id: cmake-format
      - id: cmake-lint
  - repo: https://github.com/PyCQA/pylint
    rev: 'v2.10.2'
    hooks:
      - id: pylint
        exclude: ^.trash
  - repo: https://github.com/PyCQA/isort
    rev: '5.9.3'
    hooks:
      - id: isort
  - repo: https://github.com/golangci/golangci-lint
    rev: 'v1.42.1'
    hooks:
      - id: golangci-lint
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: 'v1.26.3'
  #   hooks:
  #     - id: yamllint
  - repo: https://gist.github.com/curoky/cd141455853d28e61b61e54220a7eaa5
    rev: 'ddf614bb4efa153e3b9211a3831875ad297f411c'
    hooks:
      - id: shfmt
      - id: buildifier
      - id: clang-format
      # - id: cppcheck
      - id: bean-format
      - id: licenseheaders
        args: ['--years', '2021', '--files']
