name: gh enable IPv6

on:
  push:
    paths:
      - .github/workflows/gh-enable-ipv6.yaml
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: test ipv6
        run: ping -c 1 ipv6.google.com || echo ignore error

      - name: Set up WARP # for ipv6
        uses: fscarmen/warp-on-actions@v1.1

      - name: test ipv6
        run: ping -c 1 ipv6.google.com
